Update inventory version, fix CI
Summary:
CI is broken on `inventory` crate
```
error: failed to select a version for the requirement `inventory = "^0.1.9"`
candidate versions found which didn't match: 0.3.8
location searched: directory source `/data/sandcastle/boxes/eden-trunk-hg-fbcode-fbsource/fbcode/buck2/../../third-party/rust/vendor` (which is replacing registry `crates-io`)
```

It was updated: D47316924

Reviewed By: stepancheg

Differential Revision: D47323594

fbshipit-source-id: e11d01801ce0345c968bd15f3920bd2dcfe3e2ef