Fix dict.update docs
Summary:
passing in None to dict.update() just straight up does not work

```
[martinli@39204.od /data/sandcastle/boxes/fbsource (300697c3b6)]$ hg diff
 diff --git a/fbcode/buck2/starlark-rust/starlark/src/values/types/dict/methods.rs b/fbcode/buck2/starlark-rust/starlark/src/values/types/dict/methods.rs
 --- a/fbcode/buck2/starlark-rust/starlark/src/values/types/dict/methods.rs
+++ b/fbcode/buck2/starlark-rust/starlark/src/values/types/dict/methods.rs
@@ -283,7 +283,7 @@
     /// `D.update([pairs][, name=value[, ...])` makes a sequence of key/value
     /// insertions into dictionary D, then returns `None.`
     ///
-    /// If the positional argument `pairs` is present, it must be `None`,
+    /// If the positional argument `pairs` is present, it must be
     /// another `dict`, or some other iterable.
     /// If it is another `dict`, then its key/value pairs are inserted into D.
     /// If it is an iterable, it must provide a sequence of pairs (or other
 diff --git a/tools/build_defs/fbcode_macros/build_defs/lib/python_common.bzl b/tools/build_defs/fbcode_macros/build_defs/lib/python_common.bzl
 --- a/tools/build_defs/fbcode_macros/build_defs/lib/python_common.bzl
+++ b/tools/build_defs/fbcode_macros/build_defs/lib/python_common.bzl
@@ -1653,6 +1653,7 @@
         version_transition_required = False,
         constraint_overrides = None,
         version_selections = None):
+    {}.update(None)
     default_target_platform = default_target_platform or cxx_platform.target_platform

     maybe_inplace = python_inplace_rollout.get_package_style() if _is_fbcode_linux() else None
[martinli@39204.od /data/sandcastle/boxes/fbsource (300697c3b6)]$ buck2 build --flagfile fbcode//mode/dev fbcode//python/pylot:pylot
Starting new buck2 daemon...
Connected to new buck2 daemon.
File changed: fbcode//buck2/starlark-rust/starlark/src/values/types/dict/methods.rs
File changed: fbcode_macros//build_defs/lib/python_common.bzl
File Watcher fresh instance: new mergebase, cleared graph state, cleared dep files
Buck UI: https://www.internalfb.com/buck2/2e498f06-eb86-4cb4-b4f4-727652737635
Loading targets.   Remaining     0/1
Command: build.
Time elapsed: 0.9s
BUILD FAILED
Error evaluating build file: `fbcode//python/pylot:BUCK`

Caused by:
    Traceback (most recent call last):
      * fbcode/python/pylot/BUCK:5, in <module>
          python_binary(
      * tools/build_defs/fbcode_macros/build_defs/python_binary.bzl:94, in python_binary
          return _python_binary(
      * tools/build_defs/fbcode_macros/build_defs/python_binary.bzl:39, in _python_binary
          attributes = python_common.convert_binary(
      * tools/build_defs/fbcode_macros/build_defs/lib/python_common.bzl:2767, in _convert_binary
          binary_attributes = _single_binary_or_unittest(
      * tools/build_defs/fbcode_macros/build_defs/lib/python_common.bzl:1656, in _single_binary_or_unittest
          {}.update(None)
    error: Operation `(iter)` not supported on type `NoneType`
        --> tools/build_defs/fbcode_macros/build_defs/lib/python_common.bzl:1656:5
         |
    1656 |     {}.update(None)
         |     ^^^^^^^^^^^^^^^
         |

```

Reviewed By: JakobDegen

Differential Revision: D75702776

fbshipit-source-id: dd4484e9819631f0a69848fbdbe5b3b623076664