Add support for std::cell::LazyCell and std::sync::LazyLock
Summary:
Required in {D109642549}. Without it:

```lang=log,counterexample
Action failed: fbcode//buck2/app/buck2_execute:buck2_execute (rustc check)

error[E0277]: the trait bound `LazyLock<DashMapDirectoryInterner<..., ...>>: Allocative` is not satisfied
  --> fbcode/buck2/app/buck2_execute/src/directory.rs:71:1
   |
71 | / pub static INTERNER: LazyLock<DashMapDirectoryInterner<ActionDirectoryMember, TrackedFileDigest>> =
72 | |     LazyLock::new(DashMapDirectoryInterner::new);
   | |_________________________________________________^ unsatisfied trait bound
   |
   = help: the trait `allocative::Allocative` is not implemented for `LazyLock<DashMapDirectoryInterner<ActionDirectoryMember, TrackedCasDigest<FileDigestKind>>>`
   = help: the following other types implement trait `allocative::Allocative`:
             !
             &'static T
             ()
             (A, B)
             (A, B, C)
             (A, B, C, D)
             (A, B, C, D, E)
             (A,)
           and 931 others
   = note: required for the cast from `&LazyLock<DashMapDirectoryInterner<ActionDirectoryMember, TrackedCasDigest<FileDigestKind>>>` to `&'static (dyn allocative::Allocative + Sync + 'static)`
   = note: the full name for the type has been written to 'buck-out/v2/art/fbcode/e367a025cfe3f87c/buck2/app/buck2_execute/__buck2_execute__/LPPM/extras/libbuck2_execute/buck2_execute-7148aefc.long-type-17592921193048918400.txt'
   = note: consider using `--verbose` to print the full type name to the console
```

Reviewed By: diliop

Differential Revision: D109642548

fbshipit-source-id: 13771ebb4ff614ecf62c122dc0bc32fbdd344edc