Fix data race in PinnedPagableArc type (#232)
Summary:
When `PinnedPagableArc` is dropped the pin counter is decremented with a `Relaxed` ordering. This can result in a data race when two threads drop an owned instance of a type duplicated via `Clone`.

## Reproduction:

### Test Case:
```rust
#[test]
fn racy_test() {
    let backend = InMemoryPagableStorage::new();
    let foo = PinnedPagableArc::new(false, PagableStorageHandle::new(backend.handle()));
    let bar = foo.clone();
    std::thread::scope(|s| {
        s.spawn(move || drop(bar));
        let _read = *foo;
        drop(foo);
    });
}
```

### Running with Miri:
`MIRIFLAGS="-Zmiri-many-seeds=0..16" cargo +nightly miri test -p pagable --test repro`

### Miri output:
```
error: Undefined Behavior: Data race detected between (1) non-atomic read on thread `racy_test`
and (2) retag write of type `pagable::pagable_arc::PagableArcInnerData<bool>` on thread `unnamed-3`
at alloc768762+0x20
   --> pagable/src/pagable_arc.rs:877:44
    |
877 |                 let data: &mut _ = unsafe { &mut *ptr.data.get() };
    |                                             ^^^^^^^^^^^^^^^^^^^^ (2) just happened here
help: and (1) occurred earlier here
   --> pagable/src/pagable_arc.rs:716:14
```

## Fix:

Synchronise the `PinnedPagableArc` pin counter with `Release`/`Acquire` memory orderings and use a fence before data is unpinned.

This mirrors the synchronisation used by [`std::sync::Arc`](https://doc.rust-lang.org/src/alloc/sync.rs.html#2827).
If you'd like to see another example [I found a similar bug in the `stabby` crate](https://github.com/ZettaScaleLabs/stabby/pull/139)

Pull Request resolved: https://github.com/facebook/starlark-rust/pull/232

Reviewed By: 8Keep

Differential Revision: D117200708

Pulled By: ndmitchell

fbshipit-source-id: 0ca54c4d87d8a5314af6b58ef631da71907fe72b