Fix rustdoc links
Summary:
```lang=log,counterexample
ERROR: Documentation warning:
warning: unresolved link to `PagableArc`
  --> pagable/src/storage/data.rs:18:42
   |
18 | /// It is used to retrieve data when a [`PagableArc`] is upgraded
   |                                          ^^^^^^^^^^ no item named `PagableArc` in scope
   |
   = help: to escape `[` and `]` characters, add '\' before them like `\[` or `\]`
   = note: `#[warn(rustdoc::broken_intra_doc_links)]` on by default

ERROR: Documentation warning:
warning: could not parse code block as Rust code
  --> starlark-rust/starlark/src/values/layout/heap/branding.rs:52:5
   |
52 |   //! ```rust,ignore
   |  _____^
53 | | //! error[E0521]: borrowed data escapes outside of closure
54 | | //!   --> fbcode/buck2/starlark-rust/starlark/src/values/layout/heap/branding.rs:55:32
55 | | //!    |
...  |
66 | | //!    |                                argument requires that `'1` must outlive `'s...
67 | | //! ```
   | |_______^
   |
help: `ignore` code blocks require valid Rust code for syntax highlighting; mark blocks that do not contain Rust code as text: ```text
  --> starlark-rust/starlark/src/values/layout/heap/branding.rs:52:5
   |
52 | //! ```rust,ignore
   |     ^^^
   = note: error from rustc: unknown start of token: `
   = note: error from rustc: unknown start of token: `
   = note: error from rustc: unknown start of token: `
   = note: error from rustc: unknown start of token: `
   = note: error from rustc: unknown start of token: `
   = note: error from rustc: unknown start of token: `
   = note: error from rustc: unknown start of token: `
   = note: error from rustc: unknown start of token: `
   = note: error from rustc: unknown start of token: `
   = note: error from rustc: unknown start of token: `
   = note: error from rustc: this file contains an unclosed delimiter
   = note: `#[warn(rustdoc::invalid_rust_codeblocks)]` on by default
```

Reviewed By: diliop

Differential Revision: D92312310

fbshipit-source-id: 5e9330865350a1f222421acf0226e8919d0a0ccc